title: kevinb4
email: contact@kevinb4.com
description: >-
  A small portfolio website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevinb4.com"
github_username:  kevinb4

# Build settings
# plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
